# Site settings
title: CitySDK-ArcGIS
description: > # this means to ignore newlines until "baseurl:"
  CitySDK-ArcGIS is a module for the US Census CitySDK project to 
  connect with open data services from ArcGIS.
baseurl: "/citysdk-arcgis" # the subpath of your site, e.g. /blog/
url: "http://esridc.github.io/citysdk-arcgis" # the base hostname & protocol for your site
twitter_username: esridc
github_username:  esridc

# Build settings
markdown: kramdown
